behaviors:
  DroneMapper:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048 
      buffer_size: 40960 
      learning_rate: 0.0002 
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 5000
    checkpoint_interval: 50000